name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test_render:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r WPUB/requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Render website
      run: |
        mkdir public
        python manage.py render_static > public/index.html
    - name: Upload rendered index
      uses: actions/upload-artifact@v1
      with:
        name: index
        path: public/index.html
  
  load_deploy:
    needs: [build_test_render]
    name: Load and deploy rendered index
    runs-on: ubuntu-latest
    steps:
      - name: Load rendered index
        uses: actions/download-artifact@v1
        with:
          name: index
          path: public/index.html
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
